package backend

import (
	"fmt"
	"strings"

	"clinlang/pkg/diag"
	"clinlang/pkg/ir"
)

// Markdown renders a markdown document of the encounter.
type Markdown struct{}

func (Markdown) Name() string        { return "markdown" }
func (Markdown) ContentType() string { return "text/markdown; charset=utf-8" }

// Emit renders the case as markdown.
func (b Markdown) Emit(c *ir.Case, opts Options) ([]byte, []diag.Diagnostic, error) {
	r := renderer{opts: opts}
	e := c.Primary()

	var sb strings.Builder

	title := "Clinical Summary"
	if c.Subject.ID != "" {
		title += ": " + c.Subject.ID
	}
	fmt.Fprintf(&sb, "# %s\n\n", title)

	sb.WriteString("## Patient\n")
	fmt.Fprintf(&sb, "- **Profile**: %s\n", r.patientLine(c.Subject, c.Primary().Unit))
	if e.Context != "" {
		fmt.Fprintf(&sb, "- **Context**: %s\n", e.Context)
	}
	if len(c.Profiles) > 0 {
		fmt.Fprintf(&sb, "- **Specialty**: %s\n", strings.Join(c.Profiles, "+"))
	}
	if e.Allergies != nil {
		fmt.Fprintf(&sb, "- **Allergies**: %s\n", r.narrative(*e.Allergies))
	}
	sb.WriteString("\n")

	// ── Subjective ───────────────────────────────────────────────────────────
	sb.WriteString("## Subjective\n")
	for _, s := range sectionOrder {
		if s.Key == "pe" {
			continue
		}
		if n, ok := e.Narrative(s.Key); ok {
			fmt.Fprintf(&sb, "- **%s**: %s\n", s.Label, r.narrative(n))
		}
	}
	present, denied := splitFindings(e.Findings)
	if len(present) > 0 {
		sb.WriteString("- **Symptoms**:\n")
		for _, f := range present {
			fmt.Fprintf(&sb, "  - %s\n", r.finding(f))
		}
	}
	if len(denied) > 0 {
		fmt.Fprintf(&sb, "- **Denies**: %s\n", joinFindings(r, denied))
	}
	sb.WriteString("\n")

	// ── Objective ────────────────────────────────────────────────────────────
	sb.WriteString("## Objective\n")
	if n, ok := e.Narrative("pe"); ok {
		fmt.Fprintf(&sb, "- **Examination**: %s\n", r.narrative(n))
	}
	for _, g := range r.observationsByGroup(e) {
		fmt.Fprintf(&sb, "- **%s**:\n", g.Label)
		for _, o := range g.Items {
			if o.Value.Kind == ir.ValueFlag {
				fmt.Fprintf(&sb, "  - %s\n", r.text(o.Code))
				continue
			}
			line := fmt.Sprintf("  - %s: %s", r.text(o.Code), r.value(o.Value))
			if o.Derived {
				line += " _(derived: " + o.DerivedAs + ")_"
			}
			sb.WriteString(line + "\n")
		}
	}
	for _, sec := range ir.Present(e, c.Profiles) {
		fmt.Fprintf(&sb, "- **%s**:\n", sec.Title)
		for _, it := range sec.Items {
			fmt.Fprintf(&sb, "  - %s: %s\n", it.Label, it.Value)
		}
	}
	sb.WriteString("\n")

	// ── Assessment ───────────────────────────────────────────────────────────
	sb.WriteString("## Assessment\n")
	if len(e.Assessments) > 0 {
		fmt.Fprintf(&sb, "- **Diagnosis**: %s\n", joinCodings(r, e.Assessments))
	} else {
		sb.WriteString("- **Diagnosis**: TBD\n")
	}
	if len(e.Differentials) > 0 {
		fmt.Fprintf(&sb, "- **Differentials**: %s\n", joinCodings(r, e.Differentials))
	}
	sb.WriteString("\n")

	// ── Plan ─────────────────────────────────────────────────────────────────
	sb.WriteString("## Plan\n")
	if len(e.Orders) == 0 {
		sb.WriteString("*Not documented.*\n")
	}
	for _, o := range e.Orders {
		fmt.Fprintf(&sb, "- **%s**: %s\n", orderLabel(o.Kind), r.order(o))
	}

	if len(opts.Diagnostics) > 0 {
		sb.WriteString("\n## Notes\n")
		for _, d := range opts.Diagnostics {
			fmt.Fprintf(&sb, "- %s `%s`\n", d.Message, d.Code)
		}
	}

	sb.WriteString("\n---\n*Generated by ClinLang*\n")
	return []byte(sb.String()), nil, nil
}
